/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informacionpeliculas;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.document.Document;
import org.apache.lucene.facet.DrillDownQuery;
import org.apache.lucene.facet.DrillSideways;
import org.apache.lucene.facet.FacetResult;
import org.apache.lucene.facet.Facets;
import org.apache.lucene.facet.FacetsCollector;
import org.apache.lucene.facet.FacetsConfig;
import org.apache.lucene.facet.LabelAndValue;
import org.apache.lucene.facet.taxonomy.FastTaxonomyFacetCounts;
import org.apache.lucene.facet.taxonomy.TaxonomyReader;
import org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyReader;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.ScoreDoc;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;

/**
 *
 * @author david and daniel
 */
public class Interfaz extends javax.swing.JFrame {
    private static final String SAMPLE_CSV_FILE_PATH = "./wiki_movie_plots_deduped.csv";
    String INDEX_DIR = "./indice";
    String FACET_DIR = "./facetas";
    
    QueryParser parser = new QueryParser("text", new StandardAnalyzer());
    IndexSearcher searcher;
    TaxonomyReader taxoReader;
    Indice indice;
    List<FacetResult> storedFR;
    Query query;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() throws IOException, ParseException {
        initComponents();
        
        indice = inicializar();
    
        Directory dir = FSDirectory.open(Paths.get(INDEX_DIR));
        FSDirectory taxoDir = FSDirectory.open(Paths.get(FACET_DIR));
        IndexReader reader = DirectoryReader.open(dir);
        searcher = new IndexSearcher(reader);
        taxoReader = new DirectoryTaxonomyReader(taxoDir);
    }
    
    private Indice inicializar() throws IOException, ParseException{
        try (
            Reader reader = Files.newBufferedReader(Paths.get(SAMPLE_CSV_FILE_PATH));
            CSVReader csvReader = new CSVReaderBuilder(reader).withSkipLines(1).build();
        ) {
            String[] nextRecord;
            ArrayList<ExtraerPelicula> arrPelis = new ArrayList();
            
            while ((nextRecord = csvReader.readNext()) != null) {
                ExtraerPelicula extrPeli = new ExtraerPelicula (nextRecord);
                arrPelis.add(extrPeli);
            }
            
            Indice indice = new Indice();            
            indice.crearIndice(arrPelis);
            
            return indice;
        }
    }
    
    private void setQuery(Query q){
        this.query = q;
    }
    
    private Query getQuery(){
        return this.query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTit = new javax.swing.JLabel();
        jComboBoxEligeCampo = new javax.swing.JComboBox<>();
        jLabelInf = new javax.swing.JLabel();
        jLabelConsulta = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jButtonBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPelisEncontradas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumDocs = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCategoria = new javax.swing.JList<>();
        jLabelFaceta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListFaceta = new javax.swing.JList<>();
        jButtonCategoria = new javax.swing.JButton();
        jButtonBuscarFaceta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTit.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabelTit.setText("BUSCADOR DE PELÍCULAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabelTit, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxEligeCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Director", "Reparto", "Genero", "Origen" }));
        jComboBoxEligeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEligeCampoActionPerformed(evt);
            }
        });

        jLabelInf.setText("Campo de búsqueda");

        jLabelConsulta.setText("Consulta");

        jTextFieldBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaActionPerformed(evt);
            }
        });

        jButtonBusqueda.setText("Buscar");
        jButtonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaActionPerformed(evt);
            }
        });

        jTextAreaPelisEncontradas.setColumns(20);
        jTextAreaPelisEncontradas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPelisEncontradas);

        jLabel1.setText("Número de documentos encontrados: ");

        jLabelNumDocs.setText("0");

        jLabelCategoria.setText("Categoría");

        jScrollPane2.setViewportView(jListCategoria);

        jLabelFaceta.setText("Faceta");

        jScrollPane3.setViewportView(jListFaceta);

        jButtonCategoria.setText("Buscar categoria");
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButtonBuscarFaceta.setText("Buscar Faceta");
        jButtonBuscarFaceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarFacetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCategoria)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNumDocs))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelInf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEligeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBusqueda))
                                    .addComponent(jLabelConsulta))))
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarFaceta))
                            .addComponent(jLabelFaceta))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInf)
                            .addComponent(jLabelConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEligeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBusqueda))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoria)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNumDocs))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCategoria))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabelFaceta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarFaceta)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEligeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEligeCampoActionPerformed
        //
    }//GEN-LAST:event_jComboBoxEligeCampoActionPerformed

    private void jTextFieldBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaActionPerformed
        //
    }//GEN-LAST:event_jTextFieldBusquedaActionPerformed

    private void jButtonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaActionPerformed
        try {
            buscar(indice.getFconfig());
        } catch (ParseException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBusquedaActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        rellenarListaFacetas();
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonBuscarFacetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarFacetaActionPerformed
        try {
            buscarPorFaceta(jListCategoria.getSelectedValue());
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarFacetaActionPerformed

    private void rellenarListaFacetas(){
        String selectedCat = jListCategoria.getSelectedValue();
        ArrayList<String> arrFac = new ArrayList<String>();
        
        for (FacetResult fr : storedFR){
            if(fr.dim.equals(selectedCat)){
                for (LabelAndValue lv : fr.labelValues) {
                    arrFac.add(lv.label + " (" + lv.value + ")");
                }
                break;
            }
        }
          
        String listaFacetas[] = new String[arrFac.size()];
        listaFacetas = arrFac.toArray(listaFacetas);
        
        jListFaceta.setListData(listaFacetas);
    }
    
    private void buscarPorFaceta(String categoria) throws IOException{
        DrillDownQuery dq = new DrillDownQuery(indice.getFconfig(), getQuery());
        
        String facetaElegida = jListFaceta.getSelectedValue();
        int endIndex = facetaElegida.indexOf(" (");
        String f = facetaElegida.substring(0, endIndex);
        dq.add(categoria, f);

        DrillSideways ds = new DrillSideways(searcher, indice.getFconfig(), taxoReader);
        DrillSideways.DrillSidewaysResult dsresult = ds.search(dq,10);

        String str = "";
        for(ScoreDoc scoreDoc : dsresult.hits.scoreDocs){
           Document doc = searcher.doc(scoreDoc.doc);
           str+=scoreDoc.score + "\t\r-   "+doc.get("titulo")+"\n";
        }
        
        jTextAreaPelisEncontradas.setText(str);
        jTextAreaPelisEncontradas.update(jTextAreaPelisEncontradas.getGraphics());
        jLabelNumDocs.setText(dsresult.hits.totalHits.toString());
    }
    
    public void buscar(FacetsConfig fconfig) throws ParseException, IOException{
        
        String campo = (String)jComboBoxEligeCampo.getSelectedItem();
        campo = campo.toLowerCase();
        String consulta = (String)jTextFieldBusqueda.getText();
        
        Query q = parser.parse(campo+":\""+consulta+"\"");
        setQuery(q);

        int num_docs = 10;
        TopDocs docs = searcher.search(q,num_docs);

        //FacetsCollector
        FacetsCollector fc = new FacetsCollector();
        TopDocs tdc = FacetsCollector.search(searcher, q, num_docs, fc);

        jLabelNumDocs.setText(docs.totalHits.toString());
        
        String str = "";
        for (ScoreDoc sd : tdc.scoreDocs) {
            Document d = searcher.doc(sd.doc);
            str+=sd.score + "\t\r-   "+d.get("titulo")+"\n";
        }
        
        jTextAreaPelisEncontradas.setText(str);
        jTextAreaPelisEncontradas.update(jTextAreaPelisEncontradas.getGraphics());

        Facets facetas = new FastTaxonomyFacetCounts(taxoReader, fconfig, fc);
        
        
        List<FacetResult> TodasDims = facetas.getAllDims(100);
        storedFR = TodasDims;
        ArrayList<String> arrCat = new ArrayList<String>();
        
        for (FacetResult fr : TodasDims){
            arrCat.add(fr.dim);
        }
        
        String categorias[] = new String[arrCat.size()];
        categorias = arrCat.toArray(categorias);
        
        jListCategoria.setListData(categorias);
        jButtonCategoria.addActionListener(jComboBoxEligeCampo);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interfaz().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    protected javax.swing.JButton jButtonBuscarFaceta;
    private javax.swing.JButton jButtonBusqueda;
    protected javax.swing.JButton jButtonCategoria;
    protected javax.swing.JComboBox<String> jComboBoxEligeCampo;
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelConsulta;
    protected javax.swing.JLabel jLabelFaceta;
    private javax.swing.JLabel jLabelInf;
    protected javax.swing.JLabel jLabelNumDocs;
    private javax.swing.JLabel jLabelTit;
    protected javax.swing.JList<String> jListCategoria;
    protected javax.swing.JList<String> jListFaceta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    protected javax.swing.JTextArea jTextAreaPelisEncontradas;
    protected javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
